//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

declare module Kwip.Domain {
	export interface IEntity
	{
		id: number;
	}
	export interface IFakeEntity extends IEntity
	{
		name: string;
		rootId: number;
		parentId: number;
		parent: IFakeEntity;
		root: IFakeEntity;
		children: IFakeEntity[];
		rootCollection: IFakeEntity[];
	}
}
